server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms_class?serverTimezone=GMT&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


